### ISSUE TITLE
problems parsin config JSON

### ISSUE THREAD

**Issue by ShockiTV** [grovelabs/meteor-less#3] opened 2015-09-14 17:13 UTC
=> Errors prevented startup:                  

   While building the application:
   error: Failed to parse config/less.json as JSON

=> Your application has errors. Waiting for file change.

I created config folder in my root meteor directory.
Placed less.json from package description.
Prepared working path for index without creating actual main.less

But seems that json path is wrong or something...
With current meteor version in clean new app.

**Comment by cmnjcs** [comment] 2015-09-14 17:15
Hey, what does your JSON file look like? The error looks like there might
be an issue in that.

**Comment by ShockiTV** [comment] 2015-09-14 18:29
well, exactly same sa Readme I think

```
Roberts-MacBook-Pro:lesstest shock$ ls
client      config      lesstest.css    lesstest.html   lesstest.js
Roberts-MacBook-Pro:lesstest shock$ find *
client
client/another.less
client/myFiles.less
client/stylesheets
client/stylesheets/newStyle.less
config
config/less.json
lesstest.css
lesstest.html
lesstest.js
Roberts-MacBook-Pro:lesstest shock$ cat config/less.json 
{
    "enableAutoprefixer": true,  // defaults to false
    "autoprefixerOptions": {
        "browsers": ["> 2%", "last 2 versions"],
        "cascade": true
    },
    "useIndex": true, // defaults to false
    "indexFilePath": "client/stylesheets/main.less" // defaults ./client/main.less
}
Roberts-MacBook-Pro:lesstest shock$ cat .meteor/packages 

meteor-platform
autopublish
insecure
grove:less
Roberts-MacBook-Pro:lesstest shock$ 
```

**Comment by cmnjcs** [comment] 2015-09-14 18:37
FYI, you can make your text appear as monospace (i.e. code) by using three backticks (```). See [here](https://help.github.com/articles/github-flavored-markdown/) for reference. Makes it a lot easier to read. I've already adjusted your previous comment so I could understand it more easily.

With that noted, I will point out that the `indexFilePath` setting in `less.json` points to a file that doesn't exist. In the output of `find`, there's a `client/stylesheets/newStyle.less`, not `main.less`. When you fix that, what happens?

**Comment by ShockiTV** [comment] 2015-09-14 18:43
In readme it is mentioned that it will be autocreated.

```
Roberts-MacBook-Pro:lesstest shock$ cd client/stylesheets/
Roberts-MacBook-Pro:stylesheets shock$ touch main.less
Roberts-MacBook-Pro:stylesheets shock$ meteor
[[[[[ ~/workspace/lesstest ]]]]]              

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
^C
Roberts-MacBook-Pro:stylesheets shock$ cat main.less 
Roberts-MacBook-Pro:stylesheets shock$ 
```

**Comment by ShockiTV** [comment] 2015-09-14 18:51
Interesting is that now I am unable to reproduce that error, changing H1 color to red in default meteor scaffold works, but my less files are not added to that main.less as I would expect them to be automatically.
At least from Readme, or I still need to import them by hand ?

**Comment by cmnjcs** [comment] 2015-09-14 18:58
I'm unable to reproduce the issue on my computer. Can you please put the example in a repository so I can check it out?

**Comment by lourd** [comment] 2016-01-21 17:09
Closing this because unable to reproduce

**Closed as completed by lourd** 2016-01-21 17:09 UTC
